-- Rebuild the column to replace the unnamed V5 constraint portably, preserving every historical value.
ALTER TABLE reviewed_commit RENAME COLUMN coverage_type TO legacy_coverage_type;
ALTER TABLE reviewed_commit ADD COLUMN coverage_type VARCHAR(20) NOT NULL DEFAULT 'FULL'
    CONSTRAINT reviewed_commit_coverage_allowed CHECK (coverage_type IN ('FULL', 'EMPTY', 'METADATA_ONLY', 'MANUAL_ONLY'));
UPDATE reviewed_commit SET coverage_type = legacy_coverage_type;
ALTER TABLE reviewed_commit DROP COLUMN legacy_coverage_type;

CREATE TABLE manual_review_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reviewed_commit_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    file_path VARCHAR(1024) NOT NULL,
    old_object_sha VARCHAR(64),
    new_object_sha VARCHAR(64),
    old_mode VARCHAR(6),
    new_mode VARCHAR(6),
    reason_code VARCHAR(32) NOT NULL CHECK (reason_code IN ('SOURCE_DIFF_UNAVAILABLE', 'GIT_DIFF_BUDGET', 'AI_INPUT_LIMIT')),
    evidence_kind VARCHAR(32) NOT NULL DEFAULT 'PINNED_TREES' CHECK (evidence_kind = 'PINNED_TREES'),
    FOREIGN KEY (reviewed_commit_id, project_id) REFERENCES reviewed_commit(id, project_id),
    UNIQUE (reviewed_commit_id, file_path),
    UNIQUE (id, reviewed_commit_id, project_id),
    CHECK ((old_object_sha IS NULL AND old_mode IS NULL) OR
        (old_object_sha IS NOT NULL AND CHAR_LENGTH(old_object_sha) IN (40, 64) AND old_mode IS NOT NULL AND old_mode IN ('100644', '100755', '120000', '160000'))),
    CHECK ((new_object_sha IS NULL AND new_mode IS NULL) OR
        (new_object_sha IS NOT NULL AND CHAR_LENGTH(new_object_sha) IN (40, 64) AND new_mode IS NOT NULL AND new_mode IN ('100644', '100755', '120000', '160000'))),
    CHECK (old_object_sha IS NOT NULL OR new_object_sha IS NOT NULL)
);
ALTER TABLE review_issue ADD COLUMN issue_kind VARCHAR(20) NOT NULL DEFAULT 'AI_FINDING'
    CHECK (issue_kind IN ('AI_FINDING', 'MANUAL_REVIEW'));
ALTER TABLE review_issue ADD COLUMN manual_file_id BIGINT;
ALTER TABLE review_issue ADD COLUMN resolution_note VARCHAR(1000) NOT NULL DEFAULT '';
ALTER TABLE review_issue ALTER COLUMN severity DROP NOT NULL;
ALTER TABLE review_issue ADD CONSTRAINT review_issue_manual_link
    FOREIGN KEY (manual_file_id, reviewed_commit_id, project_id) REFERENCES manual_review_file(id, reviewed_commit_id, project_id);
ALTER TABLE review_issue ADD CONSTRAINT review_issue_manual_unique UNIQUE (manual_file_id);
ALTER TABLE review_issue ADD CONSTRAINT review_issue_kind_fields CHECK (
    (issue_kind = 'AI_FINDING' AND severity IS NOT NULL AND manual_file_id IS NULL) OR
    (issue_kind = 'MANUAL_REVIEW' AND severity IS NULL AND line_number IS NULL AND manual_file_id IS NOT NULL));
ALTER TABLE review_issue ADD CONSTRAINT review_issue_manual_resolution CHECK (
    issue_kind <> 'MANUAL_REVIEW' OR status = 'OPEN' OR CHAR_LENGTH(TRIM(resolution_note)) >= 5);
ALTER TABLE audit_event ALTER COLUMN detail TYPE VARCHAR(1200);
