CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    git_username VARCHAR(100) NOT NULL UNIQUE,
    role VARCHAR(10) NOT NULL CHECK (role IN ('ADMIN', 'USER')),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (username = LOWER(username)),
    CHECK (git_username = LOWER(git_username))
);

CREATE TABLE project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    repository_url VARCHAR(2048) NOT NULL UNIQUE,
    provider VARCHAR(10) NOT NULL CHECK (provider IN ('GITHUB', 'GITLAB')),
    repository_host VARCHAR(255) NOT NULL,
    repository_path VARCHAR(1024) NOT NULL,
    owner_id BIGINT NOT NULL REFERENCES app_user(id),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'PAUSED')),
    review_branch VARCHAR(255),
    last_reviewed_sha VARCHAR(64),
    approved_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX project_owner_idx ON project(owner_id, created_at);
CREATE INDEX project_status_idx ON project(status);

CREATE TABLE review_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id),
    status VARCHAR(20) NOT NULL CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED')),
    started_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP WITH TIME ZONE,
    reviewed_commits INTEGER NOT NULL DEFAULT 0 CHECK (reviewed_commits >= 0),
    error_message VARCHAR(1000)
);
CREATE INDEX review_run_project_idx ON review_run(project_id, started_at DESC);

CREATE TABLE reviewed_commit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id),
    commit_sha VARCHAR(64) NOT NULL,
    author_login VARCHAR(100),
    summary TEXT NOT NULL,
    reviewed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (project_id, commit_sha),
    UNIQUE (id, project_id)
);

CREATE TABLE review_issue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id),
    reviewed_commit_id BIGINT NOT NULL,
    assignee_id BIGINT NOT NULL REFERENCES app_user(id),
    severity VARCHAR(10) NOT NULL CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    title VARCHAR(240) NOT NULL,
    file_path VARCHAR(1024) NOT NULL,
    line_number INTEGER CHECK (line_number > 0),
    description TEXT NOT NULL,
    suggestion TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'RESOLVED', 'DISMISSED')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (reviewed_commit_id, project_id) REFERENCES reviewed_commit(id, project_id)
);
CREATE INDEX review_issue_assignee_idx ON review_issue(assignee_id, status, created_at DESC);
CREATE INDEX review_issue_commit_idx ON review_issue(reviewed_commit_id);

CREATE TABLE audit_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT REFERENCES app_user(id),
    action VARCHAR(80) NOT NULL,
    target_type VARCHAR(40) NOT NULL,
    target_id BIGINT,
    detail VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX audit_event_created_idx ON audit_event(created_at DESC);
