CREATE TABLE git_author_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    repository_origin VARCHAR(512) NOT NULL,
    author_email VARCHAR(320) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (repository_origin, author_email),
    CHECK (repository_origin = LOWER(repository_origin)),
    CHECK (author_email = LOWER(author_email))
);
CREATE INDEX git_author_mapping_user_idx ON git_author_mapping(user_id);
